cart_update:
    path:     /updateNum
    defaults: { _controller: DurabolBundle:Default:ajaxUpdate }

cart_cartitem_delete:
    path:     /{id}/cartdelete
    defaults: { _controller: DurabolBundle:Default:cartdelete }

cart_cartitem_deleteAjax:
    path:     /cartdeleteAjax
    defaults: { _controller: DurabolBundle:Default:cartdeleteAjax }

cart_addtocartAjax:
    path:     /addtocartAjax
    defaults: { _controller: DurabolBundle:Default:addtocartAjax }

cart_guestinfo:
    path:     /guestinfo
    defaults: { _controller: DurabolBundle:Default:guestinfo }

cart_guestinfo_es:
    path:     /es/guestinfo
    defaults: { _controller: DurabolBundle:DefaultEs:guestinfo }