category_index:
    path:     /{shop}
    defaults: { _controller: "DurabolBundle:Category:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "DurabolBundle:Category:show" }
    methods:  GET

category_new:
    path:     /{shop}/new
    defaults: { _controller: "DurabolBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{shop}/{id}/edit
    defaults: { _controller: "DurabolBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "DurabolBundle:Category:delete" }
    methods:  DELETE
