font_categoryList:
    path:     /categoryList/{shop}
    defaults: { _controller: DurabolBundle:Default:categoryList }

font_productList:
    path:     /productList/{category}
    defaults: { _controller: DurabolBundle:Default:productList }

font_post_index:
    path:     /postIndex
    defaults: { _controller: "DurabolBundle:Post:fontIndex" }

font_post_show:
    path:     /post/{id}
    defaults: { _controller: "DurabolBundle:Post:fontShow" }