font_categoryList:
    path:     /categoryList/{shop}
    defaults: { _controller: DurabolBundle:Default:categoryList }

font_productList:
    path:     /productList/{category}
    defaults: { _controller: DurabolBundle:Default:productList }

font_categoryList_es:
    path:     /es/categoryList/{shop}
    defaults: { _controller: DurabolBundle:DefaultEs:categoryList }

font_productList_es:
    path:     /es/productList/{category}
    defaults: { _controller: DurabolBundle:DefaultEs:productList }

font_post_index:
    path:     /postIndex
    defaults: { _controller: "DurabolBundle:Post:fontIndex" }

font_post_index_es:
    path:     /es/postIndex
    defaults: { _controller: "DurabolBundle:Post:fontIndexEs" }

font_post_show:
    path:     /post/{id}
    defaults: { _controller: "DurabolBundle:Post:fontShow" }

font_post_show_es:
    path:     /es/post/{id}
    defaults: { _controller: "DurabolBundle:Post:fontShowEs" }