font_categoryList:
    path:     /categoryList/{shop}
    defaults: { _controller: DurabolBundle:Default:categoryList }

font_productList:
    path:     /productList/{category}
    defaults: { _controller: DurabolBundle:Default:productList }

font_info:
    path:     /info
    defaults: { _controller: DurabolBundle:Default:info }