slider_index:
    path:     /
    defaults: { _controller: "DurabolBundle:Slider:index" }
    methods:  GET

slider_show:
    path:     /{id}/show
    defaults: { _controller: "DurabolBundle:Slider:show" }
    methods:  GET

slider_new:
    path:     /new
    defaults: { _controller: "DurabolBundle:Slider:new" }
    methods:  [GET, POST]

slider_edit:
    path:     /{id}/edit
    defaults: { _controller: "DurabolBundle:Slider:edit" }
    methods:  [GET, POST]

slider_delete:
    path:     /{id}/delete
    defaults: { _controller: "DurabolBundle:Slider:delete" }
    methods:  DELETE
