DurabolBundle\Entity\Cart:
    type: entity
    table: null
    repositoryClass: DurabolBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        state:
            type: string
            length: 255
        updateDate:
            type: datetime
    oneToOne:
        user:
            targetEntity: User
            inversedBy: cart
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        cartItems:
            targetEntity: CartItem
            mappedBy: cart
    lifecycleCallbacks: {  }
