DurabolBundle\Entity\Payment:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
