DurabolBundle\Entity\Pingtu:
    type: entity
    table: null
    repositoryClass: DurabolBundle\Repository\PingtuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        foto:
            type: string
            length: 255
        routing:
            type: string
            length: 255
        shopId:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
