DurabolBundle\Entity\Slider:
    type: entity
    table: null
    repositoryClass: DurabolBundle\Repository\SliderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        foto:
            type: string
            length: 255
        isEs:
            type: boolean
    lifecycleCallbacks: {  }
