<?php

namespace DurabolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalsRepository extends EntityRepository
{
}
