<?php

namespace DurabolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PingtuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PingtuRepository extends EntityRepository
{
}
