durabol_user:
    resource: "@DurabolBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

durabol_cart:
    resource: "@DurabolBundle/Resources/config/routing/cart.yml"
    prefix:   /cart

durabol_shop:
    resource: "@DurabolBundle/Resources/config/routing/shop.yml"
    prefix:   /admin/shop

durabol_product:
    resource: "@DurabolBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

durabol_orderinfo:
    resource: "@DurabolBundle/Resources/config/routing/orderinfo.yml"
    prefix:   /admin/orderinfo

durabol_category:
    resource: "@DurabolBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

durabol_sale:
    resource: "@DurabolBundle/Resources/config/routing/sale.yml"
    prefix:   /admin/sale

durabol_slider:
    resource: "@DurabolBundle/Resources/config/routing/slider.yml"
    prefix:   /admin/slider

durabol_font:
    resource: "@DurabolBundle/Resources/config/routing/font.yml"
    prefix:   /product

durabol_order:
    resource: "@DurabolBundle/Resources/config/routing/order.yml"
    prefix:   /order

durabol_data:
    resource: "@DurabolBundle/Resources/config/routing/data.yml"
    prefix:   /data

durabol_homepage:
    path:     /
    defaults: { _controller: DurabolBundle:Default:index }

durabol_homepage_admin:
    path:     /admin
    defaults: { _controller: DurabolBundle:Default:backEnd }

font_info:
    path:     /info
    defaults: { _controller: DurabolBundle:Default:info }